spring:
  profiles:
    active: dev

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: jpubdev
    password: qwer1234
    # driver-class-name: org.mariadb.jdbc.Driver