spring:
  profiles:
    active: local

---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: none # Make sure to disable spring.jpa.hibernate.ddl-auto if you use schema.sql.
    show-sql: true # 실행 되는 SQL문을 보여 줄지 설정
    properties:
      hibernate:
        format_sql: true # 형식화된 sql 문을 보여준다.


---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: jpubdev
    password: qwer1234
    # driver-class-name: org.mariadb.jdbc.Driver